Total cost: 0
Infeasibilities found:
Customer 4is missing
Customer 5is missing
Customer 6is missing
Customer 7is missing
Customer 8is missing
Customer 9is missing
Customer 10is missing
Customer 11is missing
Customer 12is missing
Customer 13is missing
Customer 14is missing
Customer 15is missing
Customer 16is missing
Customer 17is missing
Customer 18is missing
Customer 19is missing
Customer 20is missing
Customer 21is missing
Customer 22is missing
Customer 23is missing
